### ISSUE TITLE
undefined reference to `ParseMoney(

### ISSUE THREAD

**Issue by Bitcoin3ra** [FRCoin/Frcoin#1]
Hi. I am trying to compile your coin and I get this error by the end of the make -f makefile.unix process:

obj/wallet.o: In function `CWallet::CreateCoinStake(CKeyStore const&, unsigned int, long long, CTransaction&)':
/root/FRCoin/src/wallet.cpp:1678: undefined reference to `ParseMoney(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long long)'
collect2: error: ld returned 1 exit status
makefile.unix:166: recipe for target 'dayRevd' failed
make: *** [dayRevd] Error 1

I ran into other three errors related to the int64_t nTransactionFee and its derivatives but I could solve them easily. Sadly I don't know how to fix this last one. Any help is appreciated. I can push my files when all the compiling error are fixed to help this project. I'm running Ubuntu 16.04 LTS

**Comment by Bitcoinera** [comment]
Sorry. The whole error reads like this:

obj/init.o: In function `AppInit2()':
/root/FRCoin/src/init.cpp:438: undefined reference to `ParseMoney(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long long)'
/root/FRCoin/src/init.cpp:634: undefined reference to `ParseMoney(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long long)'
obj/main.o: In function `CreateNewBlock(CWallet*, bool)':
/root/FRCoin/src/main.cpp:4037: undefined reference to `ParseMoney(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long long)'
obj/rpcwallet.o: In function `reservebalance(std::vector<json_spirit::Value_impl<json_spirit::Config_vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<json_spirit::Value_impl<json_spirit::Config_vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&, bool)':
/root/FRCoin/src/rpcwallet.cpp:1663: undefined reference to `ParseMoney(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long long)'
obj/util.o: In function `ParseMoney(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long long&)':
/root/FRCoin/src/util.cpp:393: undefined reference to `ParseMoney(char const*, long long)'
obj/wallet.o: In function `CWallet::CreateCoinStake(CKeyStore const&, unsigned int, long long, CTransaction&)':
/root/FRCoin/src/wallet.cpp:1678: undefined reference to `ParseMoney(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long long)'
collect2: error: ld returned 1 exit status
makefile.unix:166: recipe for target 'dayRevd' failed
make: *** [dayRevd] Error 1

**Comment by Bitcoin3ra** [comment]
I could solve it. Message me if you would like to have my files.
I don't feel confident enough in git to push them :(

**Comment by FRCoin** [comment]
Compilation issues, this belongs to Windows. Thank you
