### ISSUE TITLE
 error: conflicting declaration ‘int64_t nTransactionFee’

### ISSUE THREAD

**Issue by ghost** [FRCoin/Frcoin#2]
root@vultr:~/frc/src# make -f makefile.unix
/bin/sh ../share/genbuild.sh obj/build.h
g++ -c -O2 -msse2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -I/root/frc/src -I/root/frc/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/init.d -o obj/init.o init.cpp
In file included from bitcoinrpc.h:16:0,
                 from init.cpp:7:
json/json_spirit_writer_template.h: In function ‘String_type json_spirit::non_printable_to_string(unsigned int)’:
json/json_spirit_writer_template.h:31:50: warning: typedef ‘Char_type’ locally defined but not used [-Wunused-local-typedefs]
         typedef typename String_type::value_type Char_type;
                                                  ^
In file included from init.h:8:0,
                 from init.cpp:9:
wallet.h: At global scope:
wallet.h:22:16: error: conflicting declaration ‘int64_t nTransactionFee’
 extern int64_t nTransactionFee;
                ^
In file included from db.h:8:0,
                 from init.cpp:5:
main.h:86:14: note: previous declaration as ‘int64 nTransactionFee’
 extern int64 nTransactionFee;
              ^
makefile.unix:159: recipe for target 'obj/init.o' failed
make: *** [obj/init.o] Error 1

**Comment by FRCoin** [comment]
Bug has been fixed, thank you

**Comment by ghost** [comment]
still the problem...

In file included from bitcoinrpc.h:16:0,
                 from init.cpp:7:
json/json_spirit_writer_template.h: In function ‘String_type json_spirit::non_printable_to_string(unsigned int)’:
json/json_spirit_writer_template.h:31:50: warning: typedef ‘Char_type’ locally defined but not used [-Wunused-local-typedefs]
         typedef typename String_type::value_type Char_type;
                                                  ^
In file included from init.h:8:0,
                 from init.cpp:9:
wallet.h: At global scope:
wallet.h:22:16: error: conflicting declaration ‘int64_t nTransactionFee’
 extern int64_t nTransactionFee;
                ^
In file included from db.h:8:0,
                 from init.cpp:5:
main.h:86:14: note: previous declaration as ‘int64 nTransactionFee’
 extern int64 nTransactionFee;
              ^
makefile.unix:159: recipe for target 'obj/init.o' failed
make: *** [obj/init.o] Error 1

**Comment by FRCoin** [comment]
Compilation issues, this belongs to Windows. Thank you
